/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCreate.java
 *
 * Created on Aug 7, 2017, 2:48:23 PM
 */
package com.guessbook.app;

import java.awt.Toolkit;

/**
 *
 * @author 3rd Year Account
 */
public class FrmCreate extends javax.swing.JFrame {

    /** Creates new form FrmCreate */
    public FrmCreate() {
        initComponents();
        setIcon();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCreateID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCreateName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCreateContact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCreateEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCreateGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guestbook");
        setResizable(false);
        getContentPane().setLayout(null);

        txtCreateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtCreateID);
        txtCreateID.setBounds(220, 80, 150, 26);

        jLabel6.setText("Contact Number: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 240, 140, 20);

        jLabel5.setText("Email Address: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 200, 112, 20);

        txtCreateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtCreateName);
        txtCreateName.setBounds(220, 120, 150, 26);

        jLabel3.setText("Name: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 120, 52, 20);
        getContentPane().add(txtCreateContact);
        txtCreateContact.setBounds(220, 240, 150, 26);

        jLabel4.setText("Gender: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 160, 90, 20);

        txtCreateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtCreateEmail);
        txtCreateEmail.setBounds(220, 200, 150, 26);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 48)); // NOI18N
        jLabel1.setText("Create Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, -20, 430, 150);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(220, 280, 150, 29);

        jLabel2.setText("ID: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 80, 28, 20);
        getContentPane().add(txtCreateGender);
        txtCreateGender.setBounds(220, 160, 22, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guessbook/app/create.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-810, 0, 1400, 500);

        setSize(new java.awt.Dimension(573, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtCreateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateIDActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateIDActionPerformed

private void txtCreateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateNameActionPerformed

private void txtCreateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateEmailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCreateEmailActionPerformed

private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
            if(SQLite.openDB()){
            String id = this.txtCreateID.getText();
            String name = this.txtCreateName.getText();
            String gender = this.txtCreateGender.getText();
            String email = this.txtCreateEmail.getText();
            String contact = this.txtCreateContact.getText();
            String values = id + "," + "'" + name + "'" + "," + "'" + gender + "'" + "," + "'" + email + "'" + "," + "'" + contact + "'";
            if(SQLite.create("tblGuestbook", values)){
                javax.swing.JOptionPane.showMessageDialog(null, "New Guest has been created!");
                this.dispose();
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
                this.dispose();
            }
            SQLite.closeDB();
        }    
}//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmCreate().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCreateContact;
    private javax.swing.JTextField txtCreateEmail;
    private javax.swing.JTextField txtCreateGender;
    private javax.swing.JTextField txtCreateID;
    private javax.swing.JTextField txtCreateName;
    // End of variables declaration//GEN-END:variables
}
