/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDelete.java
 *
 * Created on Aug 7, 2017, 2:57:18 PM
 */
package com.guessbook.app;

import java.awt.Toolkit;

/**
 *
 * @author 3rd Year Account
 */
public class FrmDelete extends javax.swing.JFrame {

    /** Creates new form FrmDelete */
    public FrmDelete() {
        initComponents();
        setIcon();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtDeleteID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guestbook");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 110, 17, 20);

        txtDeleteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtDeleteID);
        txtDeleteID.setBounds(190, 110, 90, 26);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        jLabel1.setText("Delete Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 430, 80);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(110, 160, 250, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guessbook/app/delete.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-630, -230, 1880, 1000);

        setSize(new java.awt.Dimension(471, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtDeleteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteIDActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtDeleteIDActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(SQLite.openDB()){
            int id = Integer.parseInt(this.txtDeleteID.getText());
            if(SQLite.delete("tblGuestbook", id)){
                javax.swing.JOptionPane.showMessageDialog(null, "Guest has been deleted!");
                this.dispose();
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
                this.dispose();
            }
            SQLite.closeDB();
        }
}//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmDelete().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDeleteID;
    // End of variables declaration//GEN-END:variables
}
