/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmUpdate.java
 *
 * Created on Aug 7, 2017, 2:55:00 PM
 */
package com.guessbook.app;

import java.awt.Toolkit;

/**
 *
 * @author 3rd Year Account
 */
public class FrmUpdate extends javax.swing.JFrame {

    /** Creates new form FrmUpdate */
    public FrmUpdate() {
        initComponents();
        setIcon();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUpdateGender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUpdateID = new javax.swing.JTextField();
        txtUpdateName = new javax.swing.JTextField();
        txtUpdateContact = new javax.swing.JTextField();
        txtUpdateEmail = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guestbook");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        jLabel1.setText("Update Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 440, 49);
        getContentPane().add(txtUpdateGender);
        txtUpdateGender.setBounds(250, 170, 23, 26);

        jLabel3.setText("Name: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 130, 52, 20);

        jLabel2.setText("ID: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 100, 28, 20);

        jLabel4.setText("Gender: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 170, 62, 20);

        jLabel5.setText("Email Address: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 200, 112, 20);

        jLabel6.setText("Contact Number: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 240, 150, 20);
        getContentPane().add(txtUpdateID);
        txtUpdateID.setBounds(250, 90, 150, 26);
        getContentPane().add(txtUpdateName);
        txtUpdateName.setBounds(250, 130, 150, 26);
        getContentPane().add(txtUpdateContact);
        txtUpdateContact.setBounds(250, 240, 150, 26);
        getContentPane().add(txtUpdateEmail);
        txtUpdateEmail.setBounds(250, 200, 150, 26);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(140, 290, 260, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/guessbook/app/update.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-1030, -620, 1660, 1150);

        setSize(new java.awt.Dimension(533, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(SQLite.openDB()){
            int id = Integer.parseInt(this.txtUpdateID.getText());
            String name = this.txtUpdateName.getText();
            String gender = this.txtUpdateGender.getText();
            String email = this.txtUpdateEmail.getText();
            String contact = this.txtUpdateContact.getText();
            String set = "NAME=" +"'"+ name + "'" + "," +"GENDER="+ "'" + gender + "'" + "," +"EMAIL_ADD="+ "'" + email + "'" + "," +"CONTACT_NO="+ "'" + contact + "'";
            if(SQLite.update("tblGuestbook", set, id)){
                
                javax.swing.JOptionPane.showMessageDialog(null, "Guest has been updated!");
                this.dispose();
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
                this.dispose();
            }
            SQLite.closeDB();
        }
       
}//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmUpdate().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtUpdateContact;
    private javax.swing.JTextField txtUpdateEmail;
    private javax.swing.JTextField txtUpdateGender;
    private javax.swing.JTextField txtUpdateID;
    private javax.swing.JTextField txtUpdateName;
    // End of variables declaration//GEN-END:variables
}
